spring:
  application:
    name: skibidi-backend
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/skibidi}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    jpa:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: skibidi-reseteo@papu.com
    password: password

server:
  port: 8091

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:FdtjVzOfOTAnd2c2G0AdgN7woPD5iFmc}
    realm: ${KEYCLOAK_REALM:skibidi-realm}
    resource: ${KEYCLOAK_RESOURCE:sk-backend}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

meta:
  path: ${META_PATH:https://graph.facebook.com/v20.0/407827362419812/messages}