spring:
  application:
    name: skibidi-backend
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/skibidi}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    jpa:
      hibernate:
        ddl-auto: none
server:
    port: 8090
