spring:
  application:
    name: skibidi-backend
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/skibidi}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    jpa:
      hibernate:
        ddl-auto: none
server:
    port: 8091

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8080}
  credentials:
    secret: ${CLIENT_SECRET:SBcbFEti8CuGOdtGZ504Siv4eW0sBD4J}
    realm: skibidi-realm
    resource: sk-backend