spring:
  application:
    name: skibidi-backend
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/skibidi}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    jpa:
      hibernate:
        ddl-auto: none
server:
    port: 8091

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8080}
  autodetect-bearer-only: true
  credentials:
    secret: ${CLIENT_SECRET:vPLcbNiPZrEcjh6Hy44Mjdt4FNbxrs6d}
    realm: skibidi-realm
    resource: sk-backend