spring:
  application:
    name: skibidi-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/skibidi
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    jpa:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8091

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8080}
  credentials:
    secret: ${CLIENT_SECRET:bT5IdnmJZkRXaG7OE74zrnwPllN2K8ux}
    realm: skibidi-realm
    resource: sk-backend