spring:
  application:
    name: skibidi-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/skibidi
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    jpa:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: skibidi-reseteo@papu.com
    password: password

server:
    port: 8091

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8080}
  credentials:
    secret: ${CLIENT_SECRET:6WPxzJN2CnFPajEbo6gVpqGrLZ5hsr0U }
    realm: skibidi-realm
    resource: sk-backend

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

meta:
  path: ${META_PATH:https://graph.facebook.com/v20.0/407827362419812/messages}